version: "3.9"

services:

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: groupme-flask
    ports:
      - "5000:5000"
    environment:
      GROUPME_BOT_ID: "${GROUPME_BOT_ID}"
    volumes:
      - ./app:/app
    restart: unless-stopped

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    container_name: groupme-streamlit
    working_dir: /app
    volumes:
      - ./streamlit:/app
    command: ["streamlit", "run", "label_refining_streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    depends_on:
      - flask-app
    restart: unless-stopped
